### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by Razanius12** [WeeXnes/NFSProStreetRPC#1]
![image](https://user-images.githubusercontent.com/100908997/156717074-f52cb239-5704-4672-a4b0-8eaa4422491d.png)
Somehow it does not work for me

**Comment by Razanius12** [comment]
![image](https://user-images.githubusercontent.com/100908997/156883469-0bd62cae-3f8b-45b4-add2-fa90378e36c4.png)
nevermind, if you run as administrator, it will eventually work

**Comment by WeeXnes** [comment]
sorry that my response comes so late, i was busy with school and had trouble getting into my github account. Im glad u fixed the issue urself, that was the exact thing i wanted to tell u to make it work. when i made the programm i forgot to make it so it requests the admin rights by itself, ill fix it soon. thanks for using my programm

**Comment by Razanius12** [comment]
Yep thanks for making the programs too
